import { useEffect, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import Loading from '../components/Loading'
import api, { errorMessage } from '../services/api'

export default function QuizPlay(){
 const {quizId}=useParams(); const navigate=useNavigate(); const started=useRef(false); const [quiz,setQuiz]=useState(null),[answers,setAnswers]=useState({}),[index,setIndex]=useState(0),[seconds,setSeconds]=useState(null),[error,setError]=useState(''),[submitting,setSubmitting]=useState(false)
 useEffect(()=>{if(started.current)return;started.current=true;api.post(`/quizzes/${quizId}/start`).then(r=>{setQuiz(r.data);setSeconds(r.data.durationMinutes*60)}).catch(e=>setError(errorMessage(e)))},[quizId])
 const submit=async()=>{if(!quiz||submitting)return;setSubmitting(true);try{const payload={answers:quiz.questions.map(q=>({questionId:q.id,selectedOptionId:answers[q.id]||null}))};const {data}=await api.post(`/attempts/${quiz.attemptId}/submit`,payload);navigate(`/result/${quiz.attemptId}`,{state:{result:data},replace:true})}catch(e){setError(errorMessage(e));setSubmitting(false)}}
 useEffect(()=>{if(seconds===null||seconds<0)return;if(seconds===0){submit();return}const t=setTimeout(()=>setSeconds(s=>s-1),1000);return()=>clearTimeout(t)},[seconds])
 if(error&&!quiz)return <div className="container py-5"><div className="alert alert-danger">{error}</div></div>; if(!quiz)return <Loading text="Preparing your quiz..."/>
 const q=quiz.questions[index]; const mm=String(Math.floor(seconds/60)).padStart(2,'0'),ss=String(seconds%60).padStart(2,'0'); const answered=Object.keys(answers).length
 return <div className="quiz-page"><div className="container py-4"><div className="quiz-topbar"><div><div className="eyebrow">{quiz.title}</div><strong>Question {index+1} of {quiz.questions.length}</strong></div><div className={`big-timer ${seconds<60?'danger':''}`}><i className="bi bi-stopwatch"/> {mm}:{ss}</div></div>{error&&<div className="alert alert-danger mt-3">{error}</div>}<div className="progress quiz-progress"><div className="progress-bar" style={{width:`${((index+1)/quiz.questions.length)*100}%`}}/></div><div className="question-card"><div className="question-kicker">Worth {q.marks} mark{q.marks!==1?'s':''}</div><h2>{q.questionText}</h2><div className="option-list">{q.options.map((o,i)=><button key={o.id} onClick={()=>setAnswers({...answers,[q.id]:o.id})} className={`answer-option ${answers[q.id]===o.id?'selected':''}`}><span>{String.fromCharCode(65+i)}</span>{o.optionText}<i className="bi bi-check-circle-fill"/></button>)}</div></div><div className="quiz-navigation"><button className="btn btn-outline-dark" disabled={index===0} onClick={()=>setIndex(index-1)}>Previous</button><span>{answered}/{quiz.questions.length} answered</span>{index<quiz.questions.length-1?<button className="btn btn-primary" onClick={()=>setIndex(index+1)}>Next</button>:<button className="btn btn-success" disabled={submitting} onClick={submit}>{submitting?'Submitting...':'Submit quiz'}</button>}</div></div></div>
}
